create table if not exists materias (
  id bigint generated by default as identity primary key,
  clave text not null,
  nombre text not null,
  descripcion text,
  activa boolean default true
);

create table if not exists grupos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  turno text not null,
  activo boolean default true
);

create table if not exists asignaciones (
  id bigint generated by default as identity primary key,
  materia_id bigint references materias(id) on delete cascade,
  grupo_id bigint references grupos(id) on delete cascade,
  activa boolean default true
);

create table if not exists perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  correo text unique not null,
  rol text not null,
  activo boolean default true,
  creado_en timestamp with time zone default now(),
  actualizado_en timestamp with time zone default now()
);

alter table materias add column if not exists activa boolean default true;
alter table grupos add column if not exists activo boolean default true;
alter table asignaciones add column if not exists activa boolean default true;
alter table perfiles add column if not exists actualizado_en timestamp with time zone default now();

do $$
declare
  c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.perfiles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%rol%'
  loop
    execute format('alter table public.perfiles drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.perfiles
add constraint perfiles_rol_check
check (rol in ('admin','alumno','docente_pendiente'));

create table if not exists alumnos (
  id bigint generated by default as identity primary key,
  perfil_id uuid references perfiles(id) on delete cascade,
  matricula text,
  grupo_id bigint references grupos(id),
  estado text default 'activo',
  creado_en timestamp with time zone default now(),
  actualizado_en timestamp with time zone default now()
);

alter table alumnos add column if not exists matricula text;
alter table alumnos add column if not exists estado text default 'activo';
alter table alumnos add column if not exists actualizado_en timestamp with time zone default now();

do $$
declare
  c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.alumnos'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%estado%'
  loop
    execute format('alter table public.alumnos drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.alumnos
add constraint alumnos_estado_check
check (estado in ('activo','baja'));

create table if not exists alumno_accesos (
  id bigint generated by default as identity primary key,
  alumno_id bigint references alumnos(id) on delete cascade,
  modulo text not null,
  habilitado boolean default true,
  actualizado_en timestamp with time zone default now()
);

do $$
declare
  c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.alumno_accesos'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%modulo%'
  loop
    execute format('alter table public.alumno_accesos drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.alumno_accesos
add constraint alumno_accesos_modulo_check
check (modulo in ('COBD','POO','MRDE'));

create table if not exists mensajes_postit (
  id bigint generated by default as identity primary key,
  alumno_id bigint references alumnos(id) on delete cascade,
  titulo text not null,
  mensaje text not null,
  visto boolean default false,
  creado_en timestamp with time zone default now()
);

create table if not exists boletas (
  id bigint generated by default as identity primary key,
  alumno_id bigint references alumnos(id) on delete cascade,
  tipo text not null,
  periodo text default '2.25.26',
  promedio numeric default 0,
  observaciones text,
  creado_en timestamp with time zone default now()
);

do $$
declare
  c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.boletas'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%tipo%'
  loop
    execute format('alter table public.boletas drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.boletas
add constraint boletas_tipo_check
check (tipo in ('preboleta','boleta'));

create table if not exists respuestas_simulador (
  id bigint generated by default as identity primary key,
  nombre text not null,
  grupo text not null,
  modulo text not null,
  actividad text not null,
  explicacion text,
  codigo text,
  salida text,
  tiempo_segundos integer default 0,
  eventos_pegado integer default 0,
  creado_en timestamp with time zone default now()
);

delete from asignaciones
where id not in (
  select min(id)
  from asignaciones
  group by materia_id, grupo_id
);

delete from grupos
where id not in (
  select min(id)
  from grupos
  group by nombre, turno
);

delete from materias
where id not in (
  select min(id)
  from materias
  group by clave
);

delete from alumno_accesos
where id not in (
  select min(id)
  from alumno_accesos
  group by alumno_id, modulo
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.materias'::regclass
      and conname = 'materias_clave_unique'
  ) then
    alter table public.materias
    add constraint materias_clave_unique unique (clave);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.grupos'::regclass
      and conname = 'grupos_nombre_turno_unique'
  ) then
    alter table public.grupos
    add constraint grupos_nombre_turno_unique unique (nombre, turno);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.asignaciones'::regclass
      and conname = 'asignaciones_materia_grupo_unique'
  ) then
    alter table public.asignaciones
    add constraint asignaciones_materia_grupo_unique unique (materia_id, grupo_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.alumno_accesos'::regclass
      and conname = 'alumno_accesos_alumno_modulo_unique'
  ) then
    alter table public.alumno_accesos
    add constraint alumno_accesos_alumno_modulo_unique unique (alumno_id, modulo);
  end if;
end $$;

insert into materias (clave, nombre, descripcion, activa) values
('COBD', 'Construcción de Bases de Datos', 'Módulo de bases de datos.', true),
('POO', 'Programación Orientada a Objetos', 'Módulo de programación orientada a objetos.', true),
('MRDE', 'Manejo de Redes', 'Módulo de manejo de redes.', true)
on conflict (clave) do update set
  nombre = excluded.nombre,
  descripcion = excluded.descripcion,
  activa = true;

insert into grupos (nombre, turno, activo) values
('410', 'Matutino', true),
('411', 'Vespertino', true),
('611', 'Matutino', true)
on conflict (nombre, turno) do update set activo = true;

insert into asignaciones (materia_id, grupo_id, activa)
select m.id, g.id, true
from materias m
join grupos g on
  (m.clave = 'COBD' and g.nombre = '410')
  or (m.clave = 'COBD' and g.nombre = '411')
  or (m.clave = 'POO' and g.nombre = '411')
  or (m.clave = 'MRDE' and g.nombre = '611')
on conflict (materia_id, grupo_id) do update set activa = true;

update perfiles set activo = true where rol = 'admin';

create table if not exists modulo_actividades (
  id bigint generated by default as identity primary key,
  modulo text not null check (modulo in ('COBD','POO','MRDE')),
  grupo text not null,
  titulo text not null,
  tipo text default 'Actividad',
  descripcion text,
  instrucciones text,
  evidencia_requerida text,
  publicada boolean default true,
  creado_en timestamp with time zone default now(),
  actualizado_en timestamp with time zone default now()
);

create table if not exists modulo_entregas (
  id bigint generated by default as identity primary key,
  actividad_id bigint references modulo_actividades(id) on delete cascade,
  alumno_id bigint references alumnos(id) on delete cascade,
  modulo text not null check (modulo in ('COBD','POO','MRDE')),
  texto text,
  archivo_nombre text,
  archivo_url text,
  estado text default 'entregada' check (estado in ('entregada','revisada','devuelta')),
  calificacion numeric,
  retroalimentacion text,
  creado_en timestamp with time zone default now(),
  actualizado_en timestamp with time zone default now()
);

insert into modulo_actividades (modulo, grupo, titulo, tipo, descripcion, instrucciones, evidencia_requerida, publicada)
select 'MRDE', '611', 'Práctica: configuración básica IOS', 'Práctica',
       'Configura interfaces, verifica conectividad y documenta el procedimiento realizado.',
       'Situación: Llegas al laboratorio y debes preparar una red básica para que dos equipos puedan comunicarse mediante un router. Realiza la configuración inicial, asigna direcciones IP, habilita interfaces y verifica conectividad. Explica con tus palabras qué hiciste y por qué cada paso era necesario.',
       'Archivo .pkt y explicación del procedimiento.', true
where not exists (
  select 1 from modulo_actividades
  where modulo = 'MRDE' and grupo = '611' and titulo = 'Práctica: configuración básica IOS'
);
