create table if not exists respuestas_simulador (
  id bigint generated by default as identity primary key,
  nombre text not null,
  grupo text not null,
  modulo text not null,
  actividad text not null,
  explicacion text not null,
  codigo text not null,
  salida text,
  tiempo_segundos integer default 0,
  eventos_pegado integer default 0,
  creado_en timestamp with time zone default now()
);
