-- Tabla para guardar actividades con simuladores/IDE.
-- Ejecutar en Supabase SQL Editor.

create table if not exists respuestas_simulador (
  id bigint generated by default as identity primary key,
  nombre text not null,
  grupo text not null,
  modulo text not null,
  actividad text not null,
  codigo text,
  explicacion text,
  resultado_pruebas jsonb,
  autenticidad jsonb,
  evaluacion_ia jsonb,
  calificacion numeric,
  retroalimentacion text,
  creado_en timestamp default now()
);

-- IMPORTANTE PARA PRUEBAS RÁPIDAS:
-- Como aún no tenemos login, habilitamos inserts anónimos temporalmente.
-- Después se debe cambiar por políticas con autenticación.

alter table respuestas_simulador enable row level security;

drop policy if exists "permitir_insert_temporal_respuestas_simulador" on respuestas_simulador;
create policy "permitir_insert_temporal_respuestas_simulador"
on respuestas_simulador
for insert
to anon
with check (true);

drop policy if exists "permitir_select_temporal_respuestas_simulador" on respuestas_simulador;
create policy "permitir_select_temporal_respuestas_simulador"
on respuestas_simulador
for select
to anon
using (true);
