create table if not exists materias (
  id bigint generated by default as identity primary key,
  clave text not null unique,
  nombre text not null,
  descripcion text,
  activa boolean default true
);

create table if not exists grupos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  turno text not null,
  activo boolean default true,
  unique(nombre, turno)
);

create table if not exists asignaciones (
  id bigint generated by default as identity primary key,
  materia_id bigint references materias(id) on delete cascade,
  grupo_id bigint references grupos(id) on delete cascade,
  activa boolean default true,
  unique(materia_id, grupo_id)
);

create table if not exists perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  correo text unique not null,
  rol text not null,
  activo boolean default true,
  creado_en timestamp with time zone default now(),
  actualizado_en timestamp with time zone default now()
);

do $$
declare
  c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.perfiles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%rol%'
  loop
    execute format('alter table public.perfiles drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.perfiles
add constraint perfiles_rol_check
check (rol in ('admin','alumno','docente_pendiente'));

create table if not exists alumnos (
  id bigint generated by default as identity primary key,
  perfil_id uuid references perfiles(id) on delete cascade,
  matricula text,
  grupo_id bigint references grupos(id),
  estado text default 'activo' check (estado in ('activo','baja')),
  creado_en timestamp with time zone default now(),
  actualizado_en timestamp with time zone default now()
);

alter table alumnos add column if not exists estado text default 'activo' check (estado in ('activo','baja'));
alter table alumnos add column if not exists actualizado_en timestamp with time zone default now();
alter table perfiles add column if not exists actualizado_en timestamp with time zone default now();

create table if not exists alumno_accesos (
  id bigint generated by default as identity primary key,
  alumno_id bigint references alumnos(id) on delete cascade,
  modulo text not null check (modulo in ('COBD','POO','MRDE')),
  habilitado boolean default true,
  actualizado_en timestamp with time zone default now(),
  unique(alumno_id, modulo)
);

create table if not exists mensajes_postit (
  id bigint generated by default as identity primary key,
  alumno_id bigint references alumnos(id) on delete cascade,
  titulo text not null,
  mensaje text not null,
  visto boolean default false,
  creado_en timestamp with time zone default now()
);

create table if not exists boletas (
  id bigint generated by default as identity primary key,
  alumno_id bigint references alumnos(id) on delete cascade,
  tipo text not null check (tipo in ('preboleta','boleta')),
  periodo text default '2.25.26',
  promedio numeric default 0,
  observaciones text,
  creado_en timestamp with time zone default now()
);

create table if not exists respuestas_simulador (
  id bigint generated by default as identity primary key,
  nombre text not null,
  grupo text not null,
  modulo text not null,
  actividad text not null,
  explicacion text,
  codigo text,
  salida text,
  tiempo_segundos integer default 0,
  eventos_pegado integer default 0,
  creado_en timestamp with time zone default now()
);

insert into materias (clave, nombre, descripcion) values
('COBD', 'Construcción de Bases de Datos', 'Módulo de bases de datos.'),
('POO', 'Programación Orientada a Objetos', 'Módulo de programación orientada a objetos.'),
('MRDE', 'Manejo de Redes', 'Módulo de manejo de redes.')
on conflict (clave) do update set
  nombre = excluded.nombre,
  descripcion = excluded.descripcion,
  activa = true;

insert into grupos (nombre, turno) values
('410', 'Matutino'),
('411', 'Vespertino'),
('611', 'Matutino')
on conflict (nombre, turno) do update set activo = true;

insert into asignaciones (materia_id, grupo_id)
select m.id, g.id from materias m, grupos g
where (m.clave = 'COBD' and g.nombre = '410')
   or (m.clave = 'COBD' and g.nombre = '411')
   or (m.clave = 'POO' and g.nombre = '411')
   or (m.clave = 'MRDE' and g.nombre = '611')
on conflict (materia_id, grupo_id) do update set activa = true;

update perfiles set activo = true where rol = 'admin';
