create table if not exists perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  correo text unique not null,
  rol text not null check (rol in ('admin','alumno')),
  activo boolean default true,
  creado_en timestamp with time zone default now()
);

create table if not exists alumnos (
  id bigint generated by default as identity primary key,
  perfil_id uuid references perfiles(id) on delete cascade,
  matricula text,
  grupo_id bigint references grupos(id),
  creado_en timestamp with time zone default now()
);
