alter table alumnos add column if not exists estado text default 'activo' check (estado in ('activo','baja'));
alter table alumnos add column if not exists actualizado_en timestamp with time zone default now();

create table if not exists alumno_accesos (
  id bigint generated by default as identity primary key,
  alumno_id bigint references alumnos(id) on delete cascade,
  modulo text not null check (modulo in ('COBD','POO','MRDE')),
  habilitado boolean default true,
  actualizado_en timestamp with time zone default now(),
  unique(alumno_id, modulo)
);

create table if not exists mensajes_postit (
  id bigint generated by default as identity primary key,
  alumno_id bigint references alumnos(id) on delete cascade,
  titulo text not null,
  mensaje text not null,
  visto boolean default false,
  creado_en timestamp with time zone default now()
);

create table if not exists boletas (
  id bigint generated by default as identity primary key,
  alumno_id bigint references alumnos(id) on delete cascade,
  tipo text not null check (tipo in ('preboleta','boleta')),
  periodo text default '2.25.26',
  promedio numeric default 0,
  observaciones text,
  creado_en timestamp with time zone default now()
);
