create table if not exists modulo_actividades (
  id bigint generated by default as identity primary key,
  modulo text not null check (modulo in ('COBD','POO','MRDE')),
  grupo text not null,
  titulo text not null,
  tipo text default 'Actividad',
  descripcion text,
  instrucciones text,
  evidencia_requerida text,
  publicada boolean default true,
  creado_en timestamp with time zone default now(),
  actualizado_en timestamp with time zone default now()
);

create table if not exists modulo_entregas (
  id bigint generated by default as identity primary key,
  actividad_id bigint references modulo_actividades(id) on delete cascade,
  alumno_id bigint references alumnos(id) on delete cascade,
  modulo text not null check (modulo in ('COBD','POO','MRDE')),
  texto text,
  archivo_nombre text,
  archivo_url text,
  estado text default 'entregada' check (estado in ('entregada','revisada','devuelta')),
  calificacion numeric,
  retroalimentacion text,
  creado_en timestamp with time zone default now(),
  actualizado_en timestamp with time zone default now()
);

insert into modulo_actividades (modulo, grupo, titulo, tipo, descripcion, instrucciones, evidencia_requerida, publicada)
select 'MRDE', '611', 'Práctica: configuración básica IOS', 'Práctica',
       'Configura interfaces, verifica conectividad y documenta el procedimiento realizado.',
       'Situación: Llegas al laboratorio y debes preparar una red básica para que dos equipos puedan comunicarse mediante un router. Realiza la configuración inicial, asigna direcciones IP, habilita interfaces y verifica conectividad. Explica con tus palabras qué hiciste y por qué cada paso era necesario.',
       'Archivo .pkt y explicación del procedimiento.', true
where not exists (
  select 1 from modulo_actividades
  where modulo = 'MRDE' and grupo = '611' and titulo = 'Práctica: configuración básica IOS'
);
