-- Opcional: tabla para recibir entregas del nuevo cuaderno de actividad.
-- Si ya tienes esta tabla, no la modifica de forma destructiva.

create table if not exists modulo_entregas (
  id bigint generated by default as identity primary key,
  actividad_id bigint references modulo_actividades(id) on delete cascade,
  alumno_id bigint references alumnos(id) on delete cascade,
  modulo text,
  texto text,
  archivo_nombre text,
  archivo_url text,
  estado text default 'entregada',
  calificacion numeric,
  retroalimentacion text,
  creado_en timestamp with time zone default now(),
  actualizado_en timestamp with time zone default now()
);

alter table modulo_entregas add column if not exists modulo text;
alter table modulo_entregas add column if not exists texto text;
alter table modulo_entregas add column if not exists archivo_nombre text;
alter table modulo_entregas add column if not exists archivo_url text;
alter table modulo_entregas add column if not exists estado text default 'entregada';
alter table modulo_entregas add column if not exists calificacion numeric;
alter table modulo_entregas add column if not exists retroalimentacion text;
alter table modulo_entregas add column if not exists actualizado_en timestamp with time zone default now();
